/// Flutter icons BuildNowIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BuildNowIcons
///      fonts:
///       - asset: fonts/BuildNowIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BuildNowIcons {
  BuildNowIcons._();

  static const _kFontFam = 'BuildNowIcons';
  static const String? _kFontPkg = null;

  static const IconData specifyicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData implement = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData design = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
